# Generated by Django 5.2.4 on 2025-07-19 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watergis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterqualitystation',
            name='measurement_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='waterqualitystation',
            name='measurement_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='waterqualitystation',
            name='number_of_samples',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='waterqualitystation',
            name='station_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='waterqualitystation',
            name='status',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
